### PR TITLE
212 move hydrolib to hydrolib core v1

### LINKED ISSUE #212: Move HYDROLIB to HYDROLIB-core v1
No failing tests when moving to hydrolib-core v1.0.0b5, so that is good news for transferring to hydrolib-core v1. However, all macos builds are failing due to https://github.com/Deltares/HYDROLIB-core/issues/972 (gcc 12 missing)

### LINKED ISSUE #227: Use consistent casing or `Laterals()` arguments
The `locationType` argument used for `Laterals()` is the only one in camelCase. The argument in the hydrolib-core codebase is lowercase, but camelcase is also supported since it is the alias. For consistency it is better to make it lowercase. Both work, as can be seen in the following code:
```python
from hydrolib.core.dflowfm.ext.models import Lateral

# works
lat_ext = Lateral(
    id="aa",
    locationtype="1d",
    numcoordinates=1,
    xcoordinates=[2],
    ycoordinates=[3],
    discharge=2,
)

# works
lat_ext = Lateral(
    id="aa",
    locationType="1d",
    numcoordinates=1,
    xcoordinates=[2],
    ycoordinates=[3],
    discharge=2,
)
```

However, if there is an actual typo an error is raised by Hydrolib-core:
```python
from hydrolib.core.dflowfm.ext.models import Lateral

# fails
lat_ext = Lateral(
    id="aa",
    locationtype_wrong="1d",
    numcoordinates=1,
    xcoordinates=[2],
    ycoordinates=[3],
    discharge=2,
)
```

This raises the following error:
```
[...]
Value error, Unknown keywords are detected in section: 'default='Lateral'', '['locationtype_wrong']'
[...]
```

### PR DESCRIPTION
**Pull request by veenstrajelmer**

### CODE REVIEW

**Comment by veenstrajelmer** [comment]
After merging with main, there are 5 failing tests:
```
=========================== short test summary info ============================
FAILED tests/dhydamo/io/test_to_hydrolibcore.py::test_convert_to_hydrolibmodel - AttributeError: 'list' object has no attribute 'filepath' and no __dict__ for setting new attributes
FAILED tests/dhydamo/io/test_to_hydrolibcore.py::test_add_to_filestructure - AttributeError: 'list' object has no attribute 'filepath' and no __dict__ for setting new attributes
FAILED tests/dhydamo/io/test_to_hydrolibcore.py::test_write_model - AttributeError: 'list' object has no attribute 'filepath' and no __dict__ for setting new attributes
FAILED tests/dhydamo/rtc/test_rtc.py::test_dimrwriter_deduplicates_coupler_items - FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/HYDROLIB/HYDROLIB/dimr_config.xml'
FAILED tests/dhydamo/rtc/test_rtc.py::test_dimrwriter_flow_to_rtc_components_for_complex_only - FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/HYDROLIB/HYDROLIB/dimr_config.xml'
===== 5 failed, 63 passed, 39 deselected, 27 warnings in 392.69s (0:06:32) =====
```

There were 50 tests before, but 13 new were added in https://github.com/Deltares/HYDROLIB/pull/200/. These are apparently not all compatible with hydrolib-core v1. Some thoughts:
- the list/filepath error is because `bnd_ext.forcingfile` is now always a list (since there can also be multiple forcingfiles). So maybe first `assert len(bnd_ext.forcingfile) == 1` (or raise a proper error) and then `bnd_ext.forcingfile[0].filepath`

**Comment by veenstrajelmer** [comment]
I have reverted commit https://github.com/Deltares/HYDROLIB/pull/213/changes/250cddfe0739746f4d03b945ca6bf1a2fc16866c since a large part of it is unrelated or even conflicting with the goal of this PR. Please put this in a separate branch+PR instead.

**Comment by veenstrajelmer** [comment]
The tests pass now, however I realized that `forcingfile` should not be a list as far as I know. I think this is a bug so I have created this issue: https://github.com/Deltares/HYDROLIB-core/issues/1076. It will be picked up as part of the hydrolib-core v1.0.1 milestone: https://github.com/Deltares/HYDROLIB-core/milestone/14. It is necessary to wait for this milestone to be completed (and for the hydrolib-core release right after that), which hopefully can be created next week.

**Review by rhutten — APPROVED** [review]
